# This is a basic workflow to help you get started with Actions
name: Deploy build code to S3

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [master]

jobs:
  AssumeRoleAndDeploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@main
    - uses: lukemorcom/react-deploy-to-s3-action-npm@v1.1.1  
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        AWS_REGION: us-west-2
        SOURCE_DIR: build
